spring:
  profiles: dev
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://13.209.235.245:3306/sasu?serverTimezone=UTC&characterEncoding=UTF-8
    username: kdg
    password: 12345

server:
  port: 8080

logging:
  config: classpath:log4j2.xml

jwt:
  key: c88d74ba-1554-48a4-b549-b926f5d77c9e

cloud:
  aws:
    credentials:
      accessKey: AKIASMUBDF3EKJTYFPPK
      secretKey: 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
    s3:
      bucket: mentor-dev-files
    region:
      static: ap-northeast-2
    stack:
      auto: false

---

spring:
  profiles: prod
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://13.209.235.245:3306/sasu?serverTimezone=UTC&characterEncoding=UTF-8
    username: kdg
    password: 12345

server:
  port: 8080

logging:
  config: classpath:log4j2.xml

jwt:
  key: c88d74ba-1554-48a4-b549-b926f5d77c9e

