server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://13.209.235.245:3306/sasu?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/sasu?serverTimezone=UTC&characterEncoding=UTF-8
    username: kdg
    password: 12345

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

