spring:
  profiles: dev
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://13.209.235.245:3306/sasu?serverTimezone=UTC&characterEncoding=UTF-8
    username: kdg
    password: 12345

server:
  port: 8080

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  config: classpath:log4j2.xml

jwt:
  key: c88d74ba-1554-48a4-b549-b926f5d77c9e

---

spring:
  profiles: prod
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://13.209.235.245:3306/sasu?serverTimezone=UTC&characterEncoding=UTF-8
    username: kdg
    password: 12345

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  config: classpath:log4j2.xml

server:
  port: 8080

jwt:
  key: c88d74ba-1554-48a4-b549-b926f5d77c9e

